---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-k8s-api-config
  namespace: flask-k8s-api
data:
  PORT: "5050"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-k8s-api-secret
  namespace: flask-k8s-api
type: Opaque
data:
  # Add your base64 encoded secrets here
  # Example: API_KEY: YXBpLWtleS1leGFtcGxl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-api
  namespace: flask-k8s-api
  labels:
    app: flask-k8s-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-k8s-api
  template:
    metadata:
      labels:
        app: flask-k8s-api
    spec:
      containers:
      - name: flask-k8s-api
        image: elpepeligroso/flask-api:latest  # Replace with your image
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
          protocol: TCP
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: flask-k8s-api-config
              key: PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: flask-k8s-api-config
              key: LOG_LEVEL
        # Add secret references if needed
        # - name: API_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: flask-k8s-api-secret
        #       key: API_